fragment PostParts on Post {
  draft
  title
  date
  body
  blocks {
    __typename
    ... on PostBlocksLongFormText {
      content
    }
    ... on PostBlocksImg {
      img
    }
    ... on PostBlocksIframe {
      url
    }
  }
  minRead
  author {
    ... on Author {
      name
      avatar
    }
    ... on Document {
      id
    }
  }
  description
  tags
  featurePost {
    __typename
    post {
      ... on Post {
        draft
        title
        date
        body
        blocks {
          __typename
          ... on PostBlocksLongFormText {
            content
          }
          ... on PostBlocksImg {
            img
          }
          ... on PostBlocksIframe {
            url
          }
        }
        minRead
        author {
          ... on Author {
            name
            avatar
          }
          ... on Document {
            id
          }
        }
        description
        tags
        featurePost {
          __typename
          post {
            ... on Post {
              draft
              title
              date
              body
              blocks {
                __typename
                ... on PostBlocksLongFormText {
                  content
                }
                ... on PostBlocksImg {
                  img
                }
                ... on PostBlocksIframe {
                  url
                }
              }
              minRead
              description
              tags
              featurePost {
                __typename
              }
              featurePosts {
                __typename
              }
            }
            ... on Document {
              id
            }
          }
        }
        featurePosts {
          __typename
          post {
            ... on Post {
              draft
              title
              date
              body
              blocks {
                __typename
                ... on PostBlocksLongFormText {
                  content
                }
                ... on PostBlocksImg {
                  img
                }
                ... on PostBlocksIframe {
                  url
                }
              }
              minRead
              description
              tags
              featurePost {
                __typename
              }
              featurePosts {
                __typename
              }
            }
            ... on Document {
              id
            }
          }
        }
      }
      ... on Document {
        id
      }
    }
  }
  featurePosts {
    __typename
    post {
      ... on Post {
        draft
        title
        date
        body
        blocks {
          __typename
          ... on PostBlocksLongFormText {
            content
          }
          ... on PostBlocksImg {
            img
          }
          ... on PostBlocksIframe {
            url
          }
        }
        minRead
        author {
          ... on Author {
            name
            avatar
          }
          ... on Document {
            id
          }
        }
        description
        tags
        featurePost {
          __typename
          post {
            ... on Post {
              draft
              title
              date
              body
              blocks {
                __typename
                ... on PostBlocksLongFormText {
                  content
                }
                ... on PostBlocksImg {
                  img
                }
                ... on PostBlocksIframe {
                  url
                }
              }
              minRead
              description
              tags
              featurePost {
                __typename
              }
              featurePosts {
                __typename
              }
            }
            ... on Document {
              id
            }
          }
        }
        featurePosts {
          __typename
          post {
            ... on Post {
              draft
              title
              date
              body
              blocks {
                __typename
                ... on PostBlocksLongFormText {
                  content
                }
                ... on PostBlocksImg {
                  img
                }
                ... on PostBlocksIframe {
                  url
                }
              }
              minRead
              description
              tags
              featurePost {
                __typename
              }
              featurePosts {
                __typename
              }
            }
            ... on Document {
              id
            }
          }
        }
      }
      ... on Document {
        id
      }
    }
  }
}

fragment AuthorParts on Author {
  name
  avatar
}
