query postAndFeaturePosts($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts2
  }
}

query postForListPage($filter: PostFilter) {
  postConnection(filter: $filter) {
    edges {
      node {
        draft
        title
        date
        description
        tags

        author {
          ... on Author {
            name
            avatar
            id
          }
        }
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
        }
      }
    }
  }
}

fragment PostParts2 on Post {
  ...PostParts
  featurePosts {
    __typename
    post {
      __typename
      ... on Document {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ... on Post {
        ...PostParts
      }
    }
  }
}
